### ISSUE TITLE
[Filter Bar] Develop and add a new filter bar component

### ISSUE THREAD

**Issue by atomworks** [future-standard/scorer-ui-kit#109]
We use the filter bar in all the projects and currently are using an older style that isn't scaling well. Instead of adding this older code to the UI Kit, there is a new design in progress for this feature.

**Comment by isacoder** [comment]
> We use the filter bar in all the projects and currently are using an older style that isn't scaling well. Instead of adding this older code to the UI Kit, there is a new design in progress for this feature.

Designs are updated now.

https://zpl.io/brGpWYO


This feature will be split in various components/issues to follow up.

### Filter section
- Filter search input
- Dropdown filter
 -- dropdown button with icon and arrow flip
 -- filter search input
 -- loading state
 -- Quantity of options displayed
 -- Options to select can be multiple or single (checkbox or radio button
- Button with icon tag style
-- More options
-- less options
-- Add search input

- Desktop Responsive Component of filter section
-- Tool that integrates the filter bar and the buttons depending of the props

- Filter Mobile version
-- Filter title
-- Filter input search
-- Filter Menu buttons
-- buttons with sub menu option
-- Add search input button
-- Sub menu filter


 
### Results 
- Amount of results number
- Filter tags list with remove option
- clear all tag option


### Sort options
 - List and multiple buttons
