### ISSUE TITLE
[Filter Bar] - Mobile Version

### ISSUE THREAD

**Issue by isacoder** [future-standard/scorer-ui-kit#150]
### Description 

This is part of a bigger feature that is Filter bar, the description of the full feature is on design issue #109

- Filter Mobile version
-- Filter title
-- Filter input search
-- Filter Menu buttons
-- buttons with sub menu option
-- Add search input button
-- Sub menu filter

design: https://zpl.io/VDmdqve

**Comment by atomworks** [comment]
Moved to project management.
