### ISSUE TITLE
"Remove" button text is hard-coded in Avatar Uploader

### ISSUE THREAD

**Issue by isacoder** [future-standard/scorer-ui-kit#170]
### Description

Currently the remove text in button of the AvatarUploader is hardcoded and that prevents localization to be used.
Should be a simple fix. 

This code is located here
https://github.com/future-standard/scorer-ui-kit/blob/b613d4b3b07f28c32df292cb971df1c5779437f2/src/Form/organisms/AvatarUploader.tsx#L196

**Comment by Onyinye91-ctrl** [comment]
@isacoder I want to work on this issue. Do you mean i should remove line 196, like all of it?
