### ISSUE TITLE
Map Functionality Research

### ISSUE THREAD

**Issue by atomworks** [future-standard/scorer-ui-kit#180]
For an upcoming project we'll need to start doing more with maps that use custom content. It seems that something like LeafletJS handles a lot of core functionality but we need to investigate how easy it will be to add our custom map layers and interactions to either that or another suitable map library.

**Comment by isacoder** [comment]
Hi, I have started a small investigation.
My previous experience with Maps was only related to Google maps.

I found this link that explains the usage of services and libraries related to maps. It's a bit old since is from November 2019 but it's good explained.

https://www.sitepen.com/blog/how-to-pick-a-web-mapping-library-for-your-app

**Comment by isacoder** [comment]
I have updated the documentation in a different [Issue](https://github.com/future-standard/surveillance-dashboard/issues/2) but I'm adding it here too to close this Issue 

# Documentation on Map Libraries

Options
https://blog.logrocket.com/react-map-library-comparison/


## Leaflet
There is a react npm package - React components for Leaflet maps
https://react-leaflet.js.org/docs/start-introduction/

LeafLet examples with react
https://codesandbox.io/s/m4k3x1ynl8

Leaflet js example
leaflet - Offline maps example youtube video
https://www.youtube.com/watch?v=oP4bCLtXIeY

Leaflet Cluster js example
https://www.youtube.com/watch?v=R-V7XFUbrkw



## MapBox
React map gl is for mapbox
https://visgl.github.io/react-map-gl/

Mapbox Examples with React
Popup example
https://codesandbox.io/s/531p2ynork
(gray example)
https://codesandbox.io/s/l7p179qr6m

Latitude and longitud on map
https://codesandbox.io/s/react-map-gl-markers-demo-m2bqr?file=/src/index.js

Mapbox colored buildings
https://codesandbox.io/s/qjnom?file=/src/index.js



Map draw a poligon
https://codesandbox.io/s/react-map-gl-draw-with-initial-features-forked-377d6?file=/src/App.js

## Map tools

### Geojson 

https://geojson.io/


### Everything maps
https://github.com/sacridini/Awesome-Geospatial#javascript
