### ISSUE TITLE
Update the bold value in typetable for lato

### ISSUE THREAD

**Issue by isacoder** [future-standard/scorer-ui-kit#182]
### Description
The font-weight is 900 should be 700 for lato

<img width="782" alt="Screen Shot 2021-09-23 at 13 30 29" src="https://user-images.githubusercontent.com/10409078/134454766-69edeb02-ab74-4571-a7c1-b6745b8dfa43.png">

**Comment by sanctum006** [comment]
Hi, can i work on this issue?

**Comment by Jayita10** [comment]
I can also work on this issue, if it is available
