### ISSUE TITLE
Investigate better solution for bundling react components.

### ISSUE THREAD

**Issue by JoshLipps** [future-standard/scorer-ui-kit#209]
At the moment building and developing storybook, GH pages and the UI kit component library is a bit fragile. It might be worth looking into Parcel or Neutrino for a better bundling / development experience. 

https://reactjs.org/docs/create-a-new-react-app.html#more-flexible-toolchains

**Comment by JoshLipps** [comment]
https://react-typescript-cheatsheet.netlify.app/docs/advanced/intro/

**Comment by atomworks** [comment]
Not sure if this one is still relevant as Josh refactored the structure of the project. It all seems to be working well so will close this.
