### ISSUE TITLE
[DatePicker] - Add a clear button

### ISSUE THREAD

**Issue by isacoder** [future-standard/scorer-ui-kit#210]
### Description

DatePicker doesn't have a way to clear the current date beyond the results clear bar ( like a button of clear). Currently clearing can only happen from the Results bar (and unfortunately the only way I was able to achieve it is umounting the picker 😞 ) . Do you want to update the UI to have a clear button or something like the searchers?.

**Comment by atomworks** [comment]
Created a task in project management for this.
