### ISSUE TITLE
[Content] - Export ContentArea to try on UI KIT

### ISSUE THREAD

**Issue by isacoder** [future-standard/scorer-ui-kit#227]
### Description

Currently when using a div in Content it will be max-width to 1400 so the first div's bellow have this issue where they need to use important to modify it, we could improve this.,

<img width="374" alt="Screen Shot 2021-11-25 at 12 28 44" src="https://user-images.githubusercontent.com/10409078/143374787-6562cae5-8af5-45fe-a080-8fc7cdc79781.png">

<img width="588" alt="Screen Shot 2021-11-25 at 12 30 39" src="https://user-images.githubusercontent.com/10409078/143374959-18bf792f-a39a-4b26-9d04-44335a6a3b5e.png">

**Comment by atomworks** [comment]
This moment has been replaced with the newer Layout components.
