### ISSUE TITLE
Filters - Update how  time condition is shown

### ISSUE THREAD

**Issue by atomworks** [future-standard/scorer-ui-kit#308]
Improve how the filter date is being shown and only include the time conditionally.

When there is a date and time selection:
2022/5/26 14:55 - 2022/5/29 19:55

When there is only a date selection:
2022/5/26 - 2022/5/29

For reference, this is a capture of how it currently appears.
![image](https://user-images.githubusercontent.com/808289/167589603-2dd05d69-e354-4ecd-b7b4-6bc530c46a8d.png)

**Comment by isacoder** [comment]
This is actually currently supported if the developer "requests" the right format.

I think is more flexible like this but let me know if you still want this to be more fixed/handeled by the DateMode and TimeMode

![Screen Shot 2022-05-11 at 17.59.37.png](https://images.zenhubusercontent.com/5d6c9cdb37b98e000186ccae/92556e72-00c6-4bcf-88e2-bdcad7c417a2)

**Comment by atomworks** [comment]
Closing. Not a UI Kit issue. Project iteration has been fixed.
