### ISSUE TITLE
[Dark-theme] - Review Issues found

### ISSUE THREAD

**Issue by isacoder** [future-standard/scorer-ui-kit#357]
- [x] Topbar Custom drawer tab icon
 
![Screen Shot 2022-07-12 at 15 15 30](https://user-images.githubusercontent.com/10409078/178421513-b1d737b2-e414-4e73-8787-e22d318ab242.png)

- [x] Alert Bar Icons should be white when inverted
![Screen Shot 2022-07-12 at 15 18 28](https://user-images.githubusercontent.com/10409078/178421995-73355fbe-2e48-42c6-9e13-ae627b69ca98.png)

- [x] Icons should be white in dark theme

![Screen Shot 2022-07-12 at 15 19 10](https://user-images.githubusercontent.com/10409078/178422095-8a264163-a57d-44bf-aec7-c510b0a799a1.png)

- [x] Sort Dropdown
 
![Screen Shot 2022-07-12 at 15 39 51](https://user-images.githubusercontent.com/10409078/178425095-1279fce9-4d92-469d-8216-979fd57ccf21.png)

- [x] Date Picker - white inputs o.o and : 

![Screen Shot 2022-07-12 at 15 40 48](https://user-images.githubusercontent.com/10409078/178425244-c834c2fe-1069-4668-ba16-8bc4a9f571cf.png)

- [x] Auto complete turning white
![Screen Shot 2022-07-12 at 15 41 47](https://user-images.githubusercontent.com/10409078/178425389-870cb58e-4b3b-4f2b-809a-c7326256c5f1.png)

![Screen Shot 2022-07-12 at 15 46 42](https://user-images.githubusercontent.com/10409078/178426215-e5cc11f9-e41c-4b39-a67a-7c51cd8e88e8.png)

 
- [x] Loading Danger version
![Screen Shot 2022-07-12 at 15 43 44](https://user-images.githubusercontent.com/10409078/178425702-9645d4ee-098d-49d3-9ce9-b7c509cc891f.png)

- [x] Area Manager Uploader - background
![Screen Shot 2022-07-12 at 15 44 51](https://user-images.githubusercontent.com/10409078/178425887-e8848f71-f090-46ed-a145-74576c78bbe2.png)

- [x] Crop tool  Icon
![Screen Shot 2022-07-12 at 15 45 50](https://user-images.githubusercontent.com/10409078/178426043-d95fe882-2a4d-4e6f-8389-889782ae3991.png)

- [x] Small Input
![Screen Shot 2022-07-12 at 15 48 03](https://user-images.githubusercontent.com/10409078/178426471-3d267a2b-e386-4458-b1ad-a7cad66cd29d.png)

- [x] Disable checkbox
![Screen Shot 2022-07-12 at 17 13 04](https://user-images.githubusercontent.com/10409078/178442812-6597d01b-b49e-4eec-99f5-2f3a8509bce5.png)

**Comment by atomworks** [comment]
Worked through many of these with the recent refactors in theme. The others will be worked through as we go and planned elsewhere.
