### ISSUE TITLE
Bug: Misreported time in filter conditions for Date Picker value of 24:00

### ISSUE THREAD

**Issue by atomworks** [future-standard/scorer-ui-kit#439]
Currently when a date picker filter is in place using the `24:00` time format, the filter conditions report this as 23:59.
![Screenshot 2024-03-05 at 17 34 01](https://github.com/future-standard/scorer-ui-kit/assets/808289/13c9f70c-8dc6-4386-b02d-bcf9cdb9fb24)

This should be fixed so the value instead reads as `00:00` the following day, as per this mockup.
![Screenshot 2024-03-05 at 17 35 08](https://github.com/future-standard/scorer-ui-kit/assets/808289/51072380-f2c3-4a45-983a-2a9d850f6307)

**Comment by isacoder** [comment]
Closing since it was fixed in PR #441
